#!/bin/bash
export DISPLAY=:0

battery_level=$(acpi -b | awk -F', |%' '{print $2}')
state=$(acpi -b | awk -F': |,' '{print $2}')

if [ $battery_level -lt 10 ] && [ $state != 'Charging' ]; then
    tinynotify-send -i battery "WARNING: Battery at $battery_level%"
fi
